name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch: # Memungkinkan trigger manual dari GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build APK (Split architecture for smaller size)
        run: flutter build apk --release --split-per-abi
        
      - name: Rename APKs
        run: |
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/KAI-Tracker-Android-Terbaru.apk
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/app/outputs/flutter-apk/KAI-Tracker-Android-Lama.apk
          
      - name: Upload APK KAI Tracker (HP Baru - 64 bit)
        uses: actions/upload-artifact@v4
        with:
          name: KAI-Tracker-Android-Terbaru
          path: build/app/outputs/flutter-apk/KAI-Tracker-Android-Terbaru.apk

      - name: Upload APK KAI Tracker (HP Lama - 32 bit)
        uses: actions/upload-artifact@v4
        with:
          name: KAI-Tracker-Android-Lama
          path: build/app/outputs/flutter-apk/KAI-Tracker-Android-Lama.apk
